name: '🏁 Sprint Management Pull Request'
title: '🏁 <Enter your PR title here!>'
description: 'Use this template for pull requests related to sprint management tasks.'
labels: ['Type: 🏁 Sprint Management PR']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Pull Request Title
        **☝️ Please provide a clear and concise title for the pull request. ☝️**

        The title should reflect the main changes proposed in the pull request. 

        **Example:** *"🏁 Implemented User-Friendly Dashboard Design"*
  - type: markdown
    attributes:
      value: |
        ## 📝 Description of the Changes
        **Provide a detailed description of the changes proposed in this pull request.**

        This should include the tasks completed, features implemented, bugs fixed, etc. 
  - type: markdown
    attributes:
      value: |
        ## 🔗 Related Issues
        **Link any related issues that this pull request addresses.**

        This could be bug reports, feature requests, or improvement proposals that are relevant to the changes made in this pull request.
  - type: markdown
    attributes:
      value: |
        ## 🔄 Proposed Changes
        **List the proposed changes in this pull request.**

        This should include any code modifications, new features, bug fixes, etc. 
  - type: markdown
    attributes:
      value: |
        ## 👀 Reviewers
        **@mention the person or team responsible for reviewing the proposed changes.**

        This could be a team lead, project manager, or other team members who are responsible for reviewing and approving the changes.
