name: 'Common: 🏢 Corporate Issue'
description: 'This template covers tasks related to company registrations, operational audits, shareholder matters, company contracts, and business regulations.'
title: '[CORPORATE ISSUE]'
labels: ['Type: 🏢 Corporate Issue']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the Corporate Issue
        A clear and concise description of what the corporate issue is.
  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the corporate issue.
      placeholder: |
        1. Describe the issue...

        2. Explain why this issue is a problem...

        3. Any additional considerations...

    validations:
      required: true
  - type: dropdown
    id: subcategory
    attributes:
      label: Which subcategory does this issue belong to?
      options: 
        - Anmeldungen & Register
        - BG, KSK, IHK
        - Betriebsprüfungen
        - Gesellschafter
        - Gesellschaftsvertrag & Geschäftsordnung
        - Gründung
        - Protokolle & Beschlüsse
        - Other
    validations:
      required: false
  - type: textarea
    attributes:
      label: Google Drive Link
      value: |
        - [Corporate](https://drive.google.com/drive/folders/0APk6c2k8TY3AUk9PVA)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Related Documents
      description: Please provide a link to any related document in the Corporate Google Drive folder or elsewhere.
      placeholder: |
        - [Document](https://www.example.com)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the issue here.
      placeholder: "Add any other context or screenshots about the issue here."
    validations:
      required: false
