name: '📋 Project Management'
description: 'This template will be used for all project-related tasks, including project planning, tracking, and management.'
labels: ['Type: Project Management 📋']
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the Project Management Issue
        A clear and concise description of what the project management issue is.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: "When I do ..., I expect ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Please select the priority of this issue.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Add any other context or screenshots about the problem here."
    validations:
      required: false
