name: '🏁 Sprint Management'
title: '🏁 <Enter your title here!>'
description: 'Use this template for tasks related to managing sprints, distributing tasks, handling resources, and managing dependencies.'
labels: ['Type: 🏁 Sprint Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Sprint Title
        **☝️ Please provide a clear and concise title for the sprint. ☝️**

        The title could reflect the main focus of the sprint, 
        the teams involved, or the project goal. 
        
        It should be short and clear, giving an idea about the sprint's aim at first glance. 

        **Example:** *"🏁 Two-Week Design Sprint for User-Friendly Dashboard Creation"*
        <br>
        👉 **Tipp:** Hold `⌘` while you click on a link, to open it in a new tab. 👈
        <br>
        <br>
  - type: markdown
    attributes:
      value: |
        ## 👟 Starting Block Meeting
        **The sprint planning starts with a monthly starting block meeting 
        with the customer that should take place in the first week of the month.**
  - type: checkboxes
    id: starting-block-meeting-checklist
    attributes:
      label: 👟 Starting Block Meeting Checklist
      description: Check off the tasks once they are completed.
      options:
        - label: Confirm and adjust **meeting time** with customer.
        - label: Prepare **meeting agenda** including discussion points and goals.
        - label: Update **project documentation** for participants' access.
        - label: Prioritize and estimate **sprint backlog** for review.
        - label: Assign **roles** for efficient meeting execution.
        - label: Dispatch **meeting invites** with necessary details.
  - type: textarea
    attributes:
      label: '📅 Starting Block Meeting'
      description: |
        Specify the meeting time and date in [Google Calendar](https://calendar.google.com/) and update the URL behind `Starting Block Meeting`.

        **Example:** ```[Starting Block Meeting](https://calendar.google.com/calendar/u/0/r/eventedit/<YOUR_EVENT_ID>)```
      value: |
        [Starting Block Meeting](URL)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 🧳 Customer Inputs
        **Link any customer-provided resources relevant for this sprint.**
        
        These can include 
        * Emails, 
        * Sketches in Figma, 
        * Asana or Miro Boards, 
        * File Downloads, etc. 
        
        Be sure to note any specific sections or features the customer has indicated as important.        
  - type: textarea
    attributes:
      label: 🧳 Customer Inputs
      placeholder: |
        The customer has provided the following resources for this sprint ...
        * [Customer email](https://mail.google.com/mail/u/0/#inbox/example)
        * [Miro Board](https://miro.com/app/board/example=/)
        * ...
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ⚙️ Sprint Planning
        **Link the appropriate *🏆 Feature Requests*, *🌟 Improvement Proposals* and *🪲 Bug Reports* from the [Backlog](https://github.com/byteyard/github-config/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone) to this sprint using GitHub's Milestones.**

        Use the `Milestone` feature in the right sidebar of each issue to add it to the appropriate sprint.   

        [Create 🏆 Feature Request](/issues/new?assignees=octocat&labels=Type%3A+%F0%9F%8F%86+Feature+Request&projects=&template=03+Feature+Request.yml&title=%F0%9F%8F%86+)
        [Create 🌟 Improvement Proposal](/issues/new?assignees=octocat&labels=Type%3A+%F0%9F%8C%9F+Improvement+Proposal&projects=&template=05+Improvement+Proposal.yml&title=%F0%9F%8C%9F+)
        [Create 🪲 Bug Report](/issues/new?assignees=octocat&labels=Type%3A+%F0%9F%AA%B2+Bug+Report&projects=&template=04+Bug+Report.yml&title=%F0%9F%AA%B2+)
  - type: markdown
    attributes:
      value: |
        ## 💣 Risks and Mitigations
        **Identify any potential risks that could impede the progress of the sprint and propose mitigation strategies.**        
  - type: textarea
    attributes:
      label: 💣 Risks and Mitigations
      placeholder: |
        The potential risks and mitigation strategies for this sprint are ...
        Example: "Risk: Delay in receiving the API from the backend team. Mitigation: Begin with creating the UI and use mock data for testing."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ⏰ Setting Time Estimates
        **Set time estimates for each task using Everhour's "Progress > Edit Estimates".**
        The `Progress > Edit Estimates` feature is located in the right sidebar of each issue. These estimates will help track progress throughout the sprint.
