name: '🏁 Sprint Management'
description: 'Use this template for tasks related to managing sprints, distributing tasks, handling resources, and managing dependencies.'
labels: ['Type: 🏁 Sprint Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Sprint Description
        Please provide a clear and concise description of the sprint or task.
  - type: textarea
    attributes:
      label: 🎯 Relevant Personnel or Teams
      description: 'List the relevant personnel or teams for this sprint.'
      placeholder: "The relevant personnel or teams for this sprint are ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🤖 Testing Requirements
      description: 'Describe the testing requirements for this sprint.'
      placeholder: "The testing requirements for this sprint are ..."
    validations:
      required: false