name: '🏁 Sprint Management'
title: '🏁 Sprint 2024-XX'
description: 'Use this template for tasks related to managing sprints, distributing tasks, handling resources, and managing dependencies.'
labels: ['Type: 🏁 Sprint Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **☝️ Please enter the correct month to the title.**
  - type: textarea
    attributes:
      label: '📅 Kick Off Meeting'
      description: |
        Specify the meeting time and date in [Google Calendar](https://calendar.google.com/) and adjust the link below accordingly.
      value: |
        [Show Kick-Off Meeting](https://calendar.google.com/)
    validations:
      required: false     
  - type: textarea
    attributes:
      label: 🧳 Customer Inputs
      description: |
        Link any customer-provided resources like Asana, Trello or Miro boards, FIGMA files, Google Docs etc., relevant for this sprint.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ✍ Meeting Notes
      description: |
        Drop noteworthy points from the kick-off meeting here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 💣 Risks and Mitigations
      description: |
        Identify any potential risks that could impede the progress of the sprint and propose mitigation strategies.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Link related issues from the [Backlog](?q=is%3Aopen+is%3Aissue+no%3Amilestone) to this sprint using GitHub's Milestones.**