name: '🏁 Sprint Management'
title: '🏁 <Enter your title here!>'
description: 'Use this template for tasks related to managing sprints, distributing tasks, handling resources, and managing dependencies.'
labels: ['Type: 🏁 Sprint Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Sprint Title
        **☝️ Please provide a clear and concise title for the sprint. ☝️**

        The title could reflect the main focus of the sprint, 
        the teams involved, or the project goal. 
        
        It should be short and clear, giving an idea about the sprint's aim at first glance. 

        **Example:** *"🏁 Two-Week Design Sprint for User-Friendly Dashboard Creation"*
  - type: markdown
    attributes:
      value: |
        ## 👟 Starting Block Meeting
        **The sprint planning begins with a monthly starting block meeting with the customer that should ideally take place in the first week of the month.**

        This section corresponds to the checklist below and aims to ensure that all preparations for the sprint are considered and acted upon.

        Please refer to the checklist for more detailed information.
  - type: checkboxes
    id: starting-block-meeting-checklist
    attributes:
      label: Starting Block Checklist
      description: Check off each task as it gets completed.
      options:
        - label: Meeting Time Adjusted
        - label: Agenda Prepared
        - label: Documentation Updated
        - label: Backlog Prioritized
        - label: Roles Assigned
        - label: Invites Dispatched
  - type: markdown
    attributes:
      value: |
        ## 🥅 Sprint Goals
        **Please specify the goals for this sprint.**

        Your goals should clearly outline what you hope to achieve by the end of the sprint. This section is connected to the 'Backlog Prioritized' task in the checklist.
  - type: textarea
    attributes:
      label: 🥅 Sprint Goals
      placeholder: |
        Example Goal: "By the end of the sprint, we aim to complete the UI for the user dashboard and commence backend integration."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 🧳 Customer Inputs
        **Please link to any customer-provided resources relevant for this sprint.**

        This includes resources such as emails, sketches in Figma, Asana or Miro boards, file downloads, etc. These customer inputs are integral to preparing the 'Documentation Updated' task in the checklist.
  - type: textarea
    attributes:
      label: 🧳 Customer Inputs
      placeholder: |
        Example: "The customer has provided us with sketches of the dashboard in Figma."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 💣 Risks and Mitigations
        **Please identify any potential risks that could impede the progress of the sprint and propose mitigation strategies.**

        Identifying risks and proposing mitigations early on helps to keep the sprint on track and is an essential part of preparing the sprint backlog.
  - type: textarea
    attributes:
      label: 💣 Risks and Mitigations
      placeholder: |
        Example: "Risk: Delay in receiving the API from the backend team. Mitigation: Begin with creating the UI and use mock data for testing."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ⚙️ Linking User Stories/Tasks
        **Link the appropriate *🏆 Feature Requests* and/or *🌟 Improvement Proposals* to this sprint using GitHub's Milestones.**

        Use the `Milestone` feature in the right sidebar of each issue to add it to the appropriate sprint.        
  - type: markdown
    attributes:
      value: |
        ## ⏰ Setting Time Estimates
        **Set time estimates for each task using Everhour's "Progress > Edit Estimates".**
        The `Progress > Edit Estimates` feature is located in the right sidebar of each issue. These estimates will help track progress throughout the sprint.
