name: '🏁 Sprint Management'
title: '🏁 <Enter your title here!>'
description: 'Use this template for tasks related to managing sprints, distributing tasks, handling resources, and managing dependencies.'
labels: ['Type: 🏁 Sprint Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Sprint Title
        **☝️ Please provide a clear and concise title for the sprint. ☝️**
  - type: markdown
    attributes:
      value: |
        ## 👟 Kick-Off Meeting
        **The sprint planning starts with a monthly kick-off meeting 
        (usually with the customer( that should take place in the first week of the month (for monthly sprints).**
  - type: checkboxes
    id: kick-off-meeting-checklist
    attributes:
      label: 👟 Kick-Off Meeting Preparation Checklist
      description: The sprint planning starts with a monthly kick-off meeting (usually with the cliint) that should take place in the first week of the month (for monthly sprints). Check off the tasks once they are completed.
      options:
        - label: Confirm and adjust **meeting time** with customer.
        - label: Prepare **meeting agenda** including discussion points and goals.
        - label: Update **project documentation** for participants' access.
        - label: Prioritize and estimate **sprint backlog** for review.
        - label: Assign **roles** for efficient meeting execution.
        - label: Dispatch **meeting invites** with necessary details.
  - type: textarea
    attributes:
      label: '📅 Kick Off Meeting'
      description: |
        Specify the meeting time and date in [Google Calendar](https://calendar.google.com/) and update the URL behind `Kick-Off Meeting`.
      value: |
        [Show Kick-Off Meeting](https://calendar.google.com/)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 🧳 Customer Inputs
        **Link any customer-provided resources relevant for this sprint.**

        * Emails, 
        * Sketches in Figma, 
        * Asana or Miro Boards, 
        * Docs or Spreadsheets
        * File Downloads, etc. 
        
        Be sure to note any specific sections or features the customer has indicated as important.        
  - type: textarea
    attributes:
      label: 🧳 Customer Inputs
      value: |
        The customer has provided the following resources for this sprint (E-Mails, Links, Files,... ) 
        
        Example:
        * [Customer email](https://mail.google.com/mail/u/0/#inbox/example)
        * [Miro Board](https://miro.com/app/board/example=/)
        * ...
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 🏃 Sprint Planning
        **Link the appropriate**
        
        * *🏆 Feature Requests*, 
        * *🌟 Improvement Proposals* and 
        * *🪲 Bug Reports* 
        
        **from the [Backlog](?q=is%3Aopen+is%3Aissue+no%3Amilestone) to this sprint using GitHub's Milestones[^1].**

        You may also use the following links to create new issues:
        
        * [🏆 Feature Request](new?assignees=octocat&labels=Type%3A+%F0%9F%8F%86+Feature+Request&projects=&template=03+Feature+Request.yml&title=%F0%9F%8F%86+)
        * [🌟 Improvement Proposal](new?assignees=octocat&labels=Type%3A+%F0%9F%8C%9F+Improvement+Proposal&projects=&template=05+Improvement+Proposal.yml&title=%F0%9F%8C%9F+)
        * [🪲 Bug Report](new?assignees=octocat&labels=Type%3A+%F0%9F%AA%B2+Bug+Report&projects=&template=04+Bug+Report.yml&title=%F0%9F%AA%B2+)

        [^1]: Use the `Milestone` feature in the right sidebar of each issue to add it to the appropriate sprint.   
  - type: textarea
    attributes:
      label: 💣 Risks and Mitigations
      description: |
        Identify any potential risks that could impede the progress of the sprint and propose mitigation strategies.
      value: |
        The potential risks and mitigation strategies for this sprint are ...

        Example: "Risk: Delay in receiving the API from the backend team. Mitigation: Begin with creating the UI and use mock data for testing."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ⏰ Setting Time Estimates
        **Set time estimates for each task using Everhour's `Progress > Edit Estimates`[^2].**
        
        [^2]: The `Progress > Edit Estimates` feature is located in the right sidebar of each issue. These estimates will help track progress throughout the sprint.
