name: '🏁 Sprint Management'
title: '🏁 Enter your title here'
description: 'Use this template for tasks related to managing sprints, distributing tasks, handling resources, and managing dependencies.'
labels: ['Type: 🏁 Sprint Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Sprint Title
        **☝️ Please provide a clear and concise title for the sprint. ☝️**

        The title could reflect the main focus of the sprint, 
        the teams involved, or the project goal. 
        
        It should be short and clear, giving an idea about the sprint's aim at first glance. 

        **Example:** *"🏁 Two-Week Design Sprint for User-Friendly Dashboard Creation"*
        <br>
  - type: markdown
    attributes:
      value: |
        ## 👟 Starting Block Meeting
        **The sprint planning starts with a monthly starting block meeting 
        with the customer that should take place in the first week of the month.**
  - type: checkboxes
    id: starting-block-meeting-checklist
    attributes:
      label: Starting Block Meeting Checklist
      description: Check off the tasks once they are completed.
      options:
        - label: Confirm meeting time with the customer
        - label: Prepare agenda for the meeting
        - label: Ensure relevant project documentation is up to date
        - label: Update and prepare sprint backlog
        - label: Assign roles for the meeting
        - label: Send out meeting invites to the team and the customer
  - type: markdown
    attributes:
      value: |
        ## 🎯 Sprint Goals
        **Specify the goals for this sprint.**

        Your goals should clearly outline what you hope to achieve by the end of the sprint.        
  - type: textarea
    attributes:
      label: 🎯 Sprint Goals
      placeholder: |
        The goals for this sprint are ...
        * Example: "By the end of the sprint, we aim to complete the UI for the user dashboard and commence backend integration."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 🧳 Customer Inputs
        **Link any customer-provided resources relevant for this sprint.**
        
        These can include 
        * emails, 
        * sketches in Figma, 
        * Asana or Miro boards, 
        * file downloads, etc. 
        
        Be sure to note any specific sections or features the customer has indicated as important.        
  - type: textarea
    attributes:
      label: 🧳 Customer Inputs
      placeholder: |
        The customer has provided the following resources for this sprint ...
        * [Customer email](https://mail.google.com/mail/u/0/#inbox/example)
        * [Miro Board](https://miro.com/app/board/example=/)
        * ...
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 💣 Risks and Mitigations
        **Identify any potential risks that could impede the progress of the sprint and propose mitigation strategies.**        
  - type: textarea
    attributes:
      label: 💣 Risks and Mitigations
      placeholder: |
        The potential risks and mitigation strategies for this sprint are ...
        Example: "Risk: Delay in receiving the API from the backend team. Mitigation: Begin with creating the UI and use mock data for testing."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ⚙️ Linking User Stories/Tasks
        **Link the appropriate *🏆 Feature Requests* and/or *🌟 Improvement Proposals* to this sprint using GitHub's Milestones.**

        Use the `Milestone` feature in the right sidebar of each issue to add it to the appropriate sprint.        
  - type: markdown
    attributes:
      value: |
        ## ⏰ Setting Time Estimates
        **Set time estimates for each task using Everhour's "Progress > Edit Estimates".**
        The `Progress > Edit Estimates` feature is located in the right sidebar of each issue. These estimates will help track progress throughout the sprint.
