name: '🏁 Sprint Management'
title: '🏁 '
description: 'Use this template for tasks related to managing sprints, distributing tasks, handling resources, and managing dependencies.'
labels: ['Type: 🏁 Sprint Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## 🏁 Sprint Description
        **Please provide a clear and concise description of the sprint.**
        This could include a short summary of the project goal, the teams involved, and the expected duration.
        Example: "This is a two-week sprint for the design team to create a user-friendly dashboard interface."
  - type: markdown
    attributes:
      value: |
        ## 🎯 Sprint Goals
        **Specify the goals for this sprint.**
        Your goals should clearly outline what you hope to achieve by the end of the sprint.
        For example: "By the end of the sprint, we aim to complete the UI for the user dashboard and commence backend integration."
  - type: textarea
    attributes:
      label: 🎯 Sprint Goals
      description: 'Describe the specific objectives for this sprint.'
      placeholder: "The goals for this sprint are ..."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 🧳 Customer Inputs
        **Link any customer-provided resources relevant for this sprint.**
        
        These can include 
        * emails, 
        * sketches in Figma, 
        * Asana or Miro boards, 
        * file downloads, etc. 
        
        Be sure to note any specific sections or features the customer has indicated as important.
  - type: textarea
    attributes:
      label: 🧳 Customer Inputs
      description: 'Provide links to or descriptions of any customer-provided resources.'
      placeholder: "The customer has provided the following resources for this sprint ..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 💣 Risks and Mitigations
        **Identify any potential risks that could impede the progress of the sprint and propose mitigation strategies.**
        Example: "Risk: Delay in receiving the API from the backend team. Mitigation: Begin with creating the UI and use mock data for testing."
  - type: textarea
    attributes:
      label: 💣 Risks and Mitigations
      description: 'Describe any potential risks and the corresponding mitigation strategies.'
      placeholder: "The potential risks and mitigation strategies for this sprint are ..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 📣 Communication Plan
        **Outline how the team will communicate during the sprint.**
        This can include stand-up meetings, sprint reviews, or any other communication method.
        Example: "Daily stand-up meetings at 9 a.m., sprint review at the end of the sprint, and ongoing communication via Slack."
  - type: textarea
    attributes:
      label: 📣 Communication Plan
      description: 'Describe the team´s communication plan for this sprint.'
      placeholder: "The communication plan for this sprint is ..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ⚙️ Linking User Stories/Tasks
        **Link the appropriate *🏆 Feature Requests* and/or *🌟 Improvement Proposals* to this sprint using GitHub's Milestones.**
        Use the `Milestone` feature in the right sidebar of each issue to add it to the appropriate sprint.
  - type: markdown
    attributes:
      value: |
        ## ⏰ Setting Time Estimates
        **Set time estimates for each task using Everhour's "Progress > Edit Estimates".**
        The `Progress > Edit Estimates` feature is located in the right sidebar of each issue. These estimates will help track progress throughout the sprint.
