name: '📝 Documentation'
title: '📝 <Enter your title here!>'
description: 'Use this template for tasks related to the creation or update of documentation.'
labels: ['Type: 📝 Documentation']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **☝️ Please provide a clear and concise title for the documentation.**

        **Example:** *"📝 API Documentation Update for New Endpoints"*
  - type: textarea
    attributes:
      label: '🎯 Reason for Change'
      description: 'Explain the reason for the documentation change (e.g., new feature, feature enhancement, discovered error).'
    validations:
      required: false     
  - type: textarea
    attributes:
      label: '📝 Documentation Outline'
      description: 'Provide an outline for the documentation.'
    validations:
      required: false     