name: '📝 Documentation'
description: 'Use this template for tasks related to the creation or update of documentation. Please provide as much information as possible to help us understand your documentation task.'
labels: ['Type: Documentation 📝']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Task 📝
        Please provide a clear and concise description of the documentation task.
  - type: textarea
    attributes:
      label: Objectives of the Documentation 🎯
      description: 'Explain the objectives of the documentation.'
      placeholder: "The objectives of this documentation are ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Target Audience 🎯
      description: 'Describe the target audience of the documentation.'
      placeholder: "The target audience of this documentation is ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context 📝
      description: 'Add any other context or screenshots about the documentation here.'
      placeholder: "Add any other context or screenshots about the documentation here."
    validations:
      required: false
