name: '📝 Documentation'
description: 'Use this template for tasks related to the creation or update of documentation.'
labels: ['Type: Documentation 📝']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Task 📝
        Please provide a clear and concise description of the documentation task.
  - type: textarea
    attributes:
      label: Reason for Change 🎯
      description: 'Explain the reason for the documentation change (e.g., new feature, feature enhancement, discovered error).'
      placeholder: "The reason for this documentation change is ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Necessary Research 📚
      description: 'Describe any necessary research to complete the documentation.'
      placeholder: "The necessary research for this documentation is ..."
    validations:
      required: false