name: '🏆 Feature Request'
title: '🏆 <Enter your title here>'
description: 'Use this template to propose new features.'
labels: ['Type: 🏆 Feature Request']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ☝️ The title should be short and descriptive.
         It should give a short preview of the proposed feature and briefly summarize the main idea.
        Example: "New dashboard widget dispaying user analytics in real time"
        A feature request can be an enhancement to an existing feature or a completely new feature. 
  - type: textarea
    attributes:
      label: '🏆 Feature Description'
      description: 'Describe the feature'
      value: "The feature should ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: '🎯 Rationale or Use Cases'
      description: 'Explain the rationale or use cases for the feature.'
      value: "The rationale or use cases for this feature are ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: '🎨 Concept Work or Design Ideas'
      description: 'Describe any concept work or design ideas for the feature.'
      value: "The concept work or design ideas for this feature are ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: '🎓 Research/Exploration'
      description: 'Describe any research or exploration that needs to be done for this feature.'
      value: "The necessary research/exploration for this feature is ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: '⛓️ Dependencies'
      description: 'List any dependencies for this feature.'
      value: "The dependencies for this feature are ..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 💻 Considerations for Code Implementation
        **Discuss any considerations for implementing the feature in code.** 
        These could be potential challenges, preferred languages or frameworks, 
        or other relevant factors. 
        Example: "Given the real-time nature of the widget, we might need to use WebSocket 
        instead of traditional HTTP requests."
  - type: textarea
    attributes:
      label: '💻 Considerations for Code Implementation'
      description: 'Describe any considerations for code implementation of the feature.'
      value: "The following aspects need to be considered: ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: '🚀 Possible Impact on Existing Features or Future Development'
      description: 'Describe the possible impact of this feature on existing features or future development.'
      value: "The possible impact of this feature on existing features or future development is ..."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: '🏃 Sprint Planning Checklist'
      description: |
        Using the right sidebar of this issue, define the task's `Time Estimate`, its `Priority Label`, and associate it with the suitable `Milestone`.
      options:
        - label: '⏰ Define a **Time Estimate** for this task.'
          required: false
        - label: '🚨 Assign a **Priority Label** to indicate the importance of the task.'
          required: false
        - label: '🏁 Link this task to a **Milestone** for inclusion in a sprint.'
          required: false
