name: '🏆 Feature Request'
description: 'Use this template to propose new features. Please provide as much information as possible to help us understand your proposal.'
labels: ['Type: Feature Request 🏆']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Description 🏆
        Please provide a clear and concise description of the feature you're proposing.
  - type: textarea
    attributes:
      label: Reason for Request 🎯
      description: 'Explain how this feature will benefit the project or its users.'
      placeholder: "This feature will improve ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Similar Existing Features 🔄
      description: 'If there are any similar features already existing, please describe them here.'
      placeholder: "The feature is similar to ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context 📝
      description: 'Add any other context or screenshots about the feature request here.'
      placeholder: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
