name: '🏆 Feature Request'
description: 'Use this template to propose new features.'
labels: ['Type: Feature Request 🏆']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Description 🏆
        Please provide a clear and concise description of the feature you're proposing.
  - type: textarea
    attributes:
      label: Rationale or Use Cases 🎯
      description: 'Explain the rationale or use cases for the feature.'
      placeholder: "The rationale or use cases for this feature are ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Concept Work or Design Ideas 🎨
      description: 'Describe any concept work or design ideas for the feature.'
      placeholder: "The concept work or design ideas for this feature are ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Considerations for Code Implementation 💻
      description: 'Describe any considerations for code implementation of the feature.'
      placeholder: "The considerations for code implementation of this feature are ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Possible Impact on Existing Features or Future Development 🚀
      description: 'Describe the possible impact of this feature on existing features or future development.'
      placeholder: "The possible impact of this feature on existing features or future development is ..."
    validations:
      required: false