name: 'ðŸª² Bug Report'
title: 'ðŸª² <Enter your title here!>'
description: 'Use this template for tasks related to reporting bugs in existing features.'
labels: ['Type: ðŸª² Bug Report']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **Tip:** When providing steps to reproduce the issue, be as detailed as possible.
        <br>
        <br>
        ## ðŸª² Bug Description
        **â˜ï¸ Clearly and concisely describe the bug. â˜ï¸**
        
        This description will provide the first glimpse into the issue at hand and should clearly convey the problem.

        **Example:** *"ðŸª² User authentication failing intermittently"*
  - type: markdown
    attributes:
      value: |
        ## ðŸ”„ Steps to Reproduce
        **The detailed steps you took when the bug occurred.**
  - type: textarea
    attributes:
      label: 'ðŸ”„ Steps to Reproduce'
      description: 'Please provide a detailed list of steps that reproduce the issue. The more detailed your steps, the easier it is for us to understand the issue.'
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## ðŸŽ¯ Expected vs Actual Outcome
        **Describe what you expected to happen versus what actually happened when you performed the steps above.**
  - type: textarea
    attributes:
      label: 'Expected Outcome ðŸŽ¯'
      description: 'Describe what you expected to happen when you performed the steps above.'
      value: "When I do ..., I expect ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Actual Outcome ðŸŽ¯'
      description: 'Describe what actually happened when you performed the steps above.'
      value: "When I do ..., I see ..."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## ðŸŒ Device, OS, and Browser Information
        **Please provide information about the device, operating system, and browser where the bug was encountered.**

        This helps us better understand the environment in which the bug occurs.
  - type: dropdown
    attributes:
      label: 'ðŸ“± Device'
      description: 'Please select the device where the bug was encountered.'
      options:
        - Desktop
        - Tablet
        - Mobile
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 'ðŸ’» Operating System'
      description: 'Please select the operating system where the bug was encountered.'
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 'ðŸŒ Browser'
      description: 'Please select the browser where the bug was encountered.'
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: 'ðŸ”„ Browser Version'
      description: 'Please enter the browser version where the bug was encountered.'
      value: "Version 90.0.4430.93 (Official Build) (64-bit)"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ðŸ“¸ Screenshots/Recordings and Additional Context
        **If applicable, add screenshots or screen recordings to help explain the bug. Add any other context about the problem here.**
  - type: textarea
    attributes:
      label: 'ðŸ“¸ Screenshots/Recordings'
      description: 'If applicable, add screenshots or screen recordings to help explain the bug.'
      value: "Upload your screenshots or recordings here."
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'ðŸ“ Additional Context'
      description: 'Add any other context about the problem here. If applicable, add screenshots to help explain your problem.'
      value: "Add any other context or screenshots about the problem here."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ðŸ’¡ Possible Solutions or Ideas
        **If you have any possible solutions or ideas, please describe them here.**
        
        Suggestions and ideas can help speed up the bug fixing process and may provide new insights into the problem.
  - type: textarea
    attributes:
      label: 'ðŸ’¡ Possible Solutions or Ideas'
      description: 'If you have any possible solutions or ideas, please describe them here.'
      value: "The possible solutions or ideas are ..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ðŸ“… Sprint Planning
        **Add a milestone[^1] to include this issue in a sprint.**

        [^1]: Use the `Milestone` feature in the right sidebar of each issue to add it to the appropriate sprint. 
  - type: markdown
    attributes:
      value: |
        ## ðŸš¨ Bug Priority
        **Before submitting this issue, please add a "Priority" label to indicate the severity of the bug.**
        
        The available "Priority" labels are:
        - Priority: Critical
        - Priority: High
        - Priority: Medium
        - Priority: Low

        These `labels`[^1] help us triage and prioritize the issue appropriately.

        [^1]: The `labels` feature is located in the right sidebar of each issue.
  - type: markdown
    attributes:
      value: |
        ## â° Setting Time Estimates
        **Set time estimates for each task using Everhour's `Progress > Edit Estimates`[^2].**
        
        [^2]: The `Progress > Edit Estimates` feature is located in the right sidebar of each issue. These estimates will help track progress throughout the sprint.
