name: '🪲 Bug Report'
title: '🪲 '
description: 'Use this template for bugs in existing features.'
labels: ['Type: 🪲 Bug Report']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **☝️  Please provide a clear and concise title for the bug.**

        **Example:** *"User authentication failing intermittently"*
  - type: dropdown
    attributes:
      label: '📱 Device'
      description: 'Select the device where the bug was encountered.'
      options:
        - All
        - Desktop
        - Tablet 
        - Mobile
        - Not relevant
    validations:
      required: false   
  - type: dropdown
    attributes:
      label: '💻 Operating System'
      description: 'Select the operating system where the bug was encountered.'
      options:
        - All
        - Windows
        - MacOS
        - iOS
        - Android
        - Other
        - Not relevant
    validations:
      required: false   
  - type: dropdown
    attributes:
      label: '🌐 Browser'
      description: 'Select the browser where the bug was encountered.'
      options:
        - All
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - Not relevant
    validations:
      required: false   
  - type: input
    attributes:
      label: '🔄 Browser Version'
      description: 'Enter the browser version where the bug was encountered.'
      placeholder: "e.g. Version 90.0.4430.93 (Official Build) (64-bit)"
    validations:
      required: false   
  - type: textarea
    attributes:
      label: '🔄 Steps to Reproduce'
      description: 'Provide a detailed list of steps to reproduce the issue.'
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false   
  - type: textarea
    attributes:
      label: '🎯 Expected Outcome'
      description: 'Describe what you expected to happen.'
      placeholder: "e.g. The page should load without any errors."
    validations:
      required: false   
  - type: textarea
    attributes:
      label: '🎯 Actual Outcome'
      description: 'Describe what actually happened.'
      placeholder: "e.g. An error message appeared on the screen."
    validations:
      required: false   
  - type: textarea
    attributes:
      label: '📸 Screenshots/Recordings'
      description: 'If applicable, add screenshots or screen recordings to help explain the bug.'
    validations:
      required: false   
  - type: textarea
    attributes:
      label: '📝 Additional Context'
      description: 'Add any other context about the problem here.'
    validations:
      required: false   
  - type: textarea
    attributes:
      label: '💡 Possible Solutions or Ideas'
      description: 'If you have any possible solutions or ideas, please describe them here.'
    validations:
      required: false
