name: '🔄 Improvement Proposal'
description: 'This template will be used for suggesting enhancements to existing features or processes.'
title: '[IMPROVEMENT PROPOSAL]'
labels: ['Type: Project Improvement']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the Improvement Proposal
        A clear and concise description of what the improvement proposal is.
  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the proposed improvement.
      placeholder: |
        1. Describe the improvement...
        2. Explain why this improvement is needed...
        3. Any additional considerations...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Describe a use case for this improvement.
      placeholder: "When I do ..., this improvement would ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Please select the priority of this improvement proposal.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the improvement proposal here.
      placeholder: "Add any other context or screenshots about the improvement proposal here."
    validations:
      required: false
