name: '🌟 Improvement Proposal'
description: 'Use this template to suggest enhancements to existing features or processes. Please provide as much information as possible to help us understand your proposal.'
labels: ['Type: Improvement Proposal 🌟']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Improvement Description 🌟
        Please provide a clear and concise description of the improvement you're proposing.
  - type: textarea
    attributes:
      label: Reason for Proposal 🎯
      description: 'Explain how this improvement will benefit the project or its users.'
      placeholder: "This improvement will enhance ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Similar Existing Features or Processes 🔄
      description: 'If there are any similar features or processes already existing, please describe them here.'
      placeholder: "The improvement is related to ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context 📝
      description: 'Add any other context or screenshots about the improvement proposal here.'
      placeholder: "Add any other context or screenshots about the improvement proposal here."
    validations:
      required: false
