name: '🔭 Research/Exploration'
description: 'Use this template for tasks that require initial research or exploration. Please provide as much information as possible to help us understand your research topic.'
labels: ['Type: Research/Exploration 🔭']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Research Topic 🔭
        Please provide a clear and concise description of the research topic.
  - type: textarea
    attributes:
      label: Objectives of the Research 🎯
      description: 'Explain the objectives of the research.'
      placeholder: "The objectives of this research are ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Background Information 📚
      description: 'If there's any relevant background information, please describe it here.'
      placeholder: "The background information of this research is ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context 📝
      description: 'Add any other context or screenshots about the research here.'
      placeholder: "Add any other context or screenshots about the research here."
    validations:
      required: false
