name: '🌈 Design'
description: 'Use this template for tasks that require design input or are related to UI/UX. Please provide as much information as possible to help us understand your design task.'
labels: ['Type: Design 🌈']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Design Task 🌈
        Please provide a clear and concise description of the design task.
  - type: textarea
    attributes:
      label: Objectives of the Design 🎯
      description: 'Explain the objectives of the design.'
      placeholder: "The objectives of this design are ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context 📝
      description: 'Add any other context or screenshots about the design here.'
      placeholder: "Add any other context or screenshots about the design here."
    validations:
      required: false
