name: '🌟 Improvement Request'
description: 'Use this template for enhancements or modifications to existing features.'
labels: ['Type: 🌟 Improvement Proposal']
assignees:
  - octocat
title: '🌟 '
body:
  - type: markdown
    attributes:
      value: |
        **☝️  Please provide a clear and concise title for the improvement request.**

        **Example:** "Enhance dashboard widget to display user analytics in real time."
  - type: textarea
    attributes:
      label: '🌟 Improvement Description'
      description: 'Describe the improvement in detail.'
    validations:
      required: false
  - type: textarea
    attributes:
      label: '🎯 Rationale for Enhancement'
      description: 'Detail the reasoning behind the improvement and what it tries to achieve ultimately.'
    validations:
      required: false
  - type: textarea
    attributes:
      label: '🎨 Concept Work or Design Specifications'
      description: 'Add any conceptual outlines or design specs for the enhancement.'
    validations:
      required: false
  - type: textarea
    attributes:
      label: '🚀 Possible Impact on the Existing Feature or Future Development'
      description: 'Describe the possible impact of this improvement on the existing feature or future development.'
    validations:
      required: false
