name: '💾 Dependency'
description: 'Use this template for issues related to third-party libraries, tools, or system integrations. Please provide as much information as possible to help us understand your issue.'
labels: ['Type: Dependency 💾']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Dependency Issue 💾
        Please provide a clear and concise description of the dependency issue.
  - type: textarea
    attributes:
      label: Impact of the Issue 🎯
      description: 'Explain how this issue impacts the project.'
      placeholder: "This issue impacts the project by ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce 🔄
      description: 'If applicable, provide a detailed list of steps that reproduce the issue.'
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context 📝
      description: 'Add any other context or screenshots about the dependency issue here.'
      placeholder: "Add any other context or screenshots about the dependency issue here."
    validations:
      required: false
