name: '🔔 Generic To Do'
title: '🔔 <Enter your title here>'
description: 'Use this template for any generic to dos within a project that do not fit the other issue types.'
labels: ['Type: 🔔 Generic To Do']
assignees:
  - octocat
body:
  - type: textarea
    attributes:
      label: '🔔 To Do Description'
      description: 'Describe the to do in detail (optional).'
    validations:
      required: false   
  - type: textarea
    attributes:
      label: '📚 Additional Context and Information'
      description: 'Add relevant context or information (optional).'
    validations:
      required: false   