name: '🤖 Testing'
description: 'This template will be used for tasks related to testing (unit, integration, etc.).'
labels: ['Type: Testing 🤖']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the Testing Task
        A clear and concise description of what the testing task is.
  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the testing task.
      placeholder: |
        1. Describe the task...
        2. Explain why this task is needed...
        3. Any additional considerations...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Outcome
      description: Describe the expected outcome of this task.
      placeholder: "After completing this task, we should know ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Please select the priority of this task.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the task here.
      placeholder: "Add any other context or screenshots about the task here."
    validations:
      required: false
