name: '🤖 Testing'
description: 'Use this template for tasks related to testing (unit, integration, etc.). Please provide as much information as possible to help us understand your testing task.'
labels: ['Type: Testing 🤖']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Testing Task 🤖
        Please provide a clear and concise description of the testing task.
  - type: textarea
    attributes:
      label: Objectives of the Testing 🎯
      description: 'Explain the objectives of the testing.'
      placeholder: "The objectives of this testing are ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Testing Environment 🌐
      description: 'Please select the environment where the testing will be performed.'
      options:
        - Development
        - Staging
        - Production
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results 🎯
      description: 'Describe what you expect to happen as a result of the testing.'
      placeholder: "The expected results of this testing are ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results 🎯
      description: 'Describe what actually happened as a result of the testing.'
      placeholder: "The actual results of this testing are ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context 📝
      description: 'Add any other context or screenshots about the testing here.'
      placeholder: "Add any other context or screenshots about the testing here."
    validations:
      required: false
