name: 'Project: 💡 Feature Request'
description: 'This template will be used for proposing new features.'
title: '[FEATURE REQUEST]'
labels: ['Type: Project Feature Request']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the Feature Request
        A clear and concise description of what the feature request is.
  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the proposed feature.
      placeholder: |
        1. Describe the feature...
        2. Explain why this feature is needed...
        3. Any additional considerations...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Describe a use case for this feature.
      placeholder: "When I do ..., this feature would ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Please select the priority of this feature request.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
      placeholder: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
