name: Marketing Issue
description: 'This template covers all marketing-related tasks, including marketing strategies, content creation, campaign planning, lead generation, customer relationship management, etc.'
title: '[MARKETING ISSUE]'
labels: ['Type: Marketing']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the Marketing Issue
        A clear and concise description of what the marketing issue is.
  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the marketing issue.
      placeholder: |
        1. Describe the issue...
        2. Explain why this issue is a problem...
        3. Any additional considerations...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Outcome
      description: Describe the expected outcome of resolving this issue.
      placeholder: "After resolving this issue, we should ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Please select the priority of this issue.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the issue here.
      placeholder: "Add any other context or screenshots about the issue here."
    validations:
      required: false
