name: Project Management Issue
description: 'This template will be used for project-related tasks, including project planning, tracking, and management.'
title: '[PROJECT MANAGEMENT]'
labels: ['Type: Project Management']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the task
        A clear and concise description of what the task is.
  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the task.
      placeholder: |
        1. Task objective
        2. Expected outcome
        3. Any specific requirements
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Please select the priority of this task.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the task here.
      placeholder: "Add any other context or screenshots about the task here."
    validations:
      required: false
