name: 🪲 Project Bug Report
description: 'This template will be used for reporting bugs or issues.'
title: '[BUG]'
labels: ['Type: Bug']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug
        A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: "When I do ..., I expect ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Device
      description: Please select the device where the bug was encountered.
      options:
        - Desktop
        - Tablet
        - Mobile
    validations:
      required: true
  - type: dropdown
    attributes:
      label: OS
      description: Please select the operating system where the bug was encountered.
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Browser
      description: Please select the browser where the bug was encountered.
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Browser Version
      description: Please enter the browser version.
      placeholder: "Version 90.0.4430.93 (Official Build) (64-bit)"
    validations:
      required: false    
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Add any other context or screenshots about the problem here."
    validations:
      required: false
