name: 🔬 Project Research/Exploration
description: 'This template will be used for tasks that require initial research or exploration.'
title: '[RESEARCH/EXPLORATION]'
labels: ['Type: Project Research']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the Research/Exploration Task
        A clear and concise description of what the research or exploration task is.
  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the research or exploration task.
      placeholder: |
        1. Describe the task...
        2. Explain why this task is needed...
        3. Any additional considerations...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Outcome
      description: Describe the expected outcome of this task.
      placeholder: "After completing this task, we should know ..."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: Please select the priority of this task.
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the task here.
      placeholder: "Add any other context or screenshots about the task here."
    validations:
      required: false
