name: Autofill PR description

on: pull_request

jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04

    steps:
      - uses: platisd/openai-pr-description@master
        with:
          github_token: ${{ secrets.BYTEYARD_GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.BYTEYARD_OPENAI_API_KEY }}